image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/hcx-api"
env:
  bootstrap_servers: "{{ groups['kafka'][0] }}:9092"
  kafka_payload_topic: "{{ env }}.hcx.request.payload"
  kafka_coverageeligibility_topic: "{{ env }}.hcx.request.coverageeligibility"
  kafka_preauth_topic: "{{ env }}.hcx.request.preauth"
  kafka_claim_topic: "{{ env }}.hcx.request.claim"
  kafka_payment_topic: "{{ env }}.hcx.request.payment"
  postgres_url: "jdbc:postgresql://terraform-20211111045938760100000001.culmyp72rbwi.ap-south-1.rds.amazonaws.com:5432/postgres"
  elasticsearch_url: "10.0.1.18:9200"
  postgres_user: "hcxpostgresql"
  postgres_password: "SuperSecurePassword"
  postgres_tablename: "payload"
  registry_basePath: "http://hcx-registry.dev.svc.cluster.local:8081"
