image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/hcx-api"
env:
  bootstrap_servers: "{{ groups['kafka'][0] }}:9092"
  kafka_payload_topic: "{{ env }}.hcx.request.payload"
  kafka_coverageeligibility_topic: "{{ env }}.hcx.request.coverageeligibility"
  kafka_preauth_topic: "{{ env }}.hcx.request.preauth"
  kafka_claim_topic: "{{ env }}.hcx.request.claim"
  kafka_payment_topic: "{{ env }}.hcx.request.payment"
  kafka_search_topic: "{{ env }}.hcx.request.search"
  kafka_search_response_topic: "{{ env }}.hcx.response.search"
  kafka_status_topic: "{{ env }}.hcx.request.status.search"
  kafka_communication_topic: "{{ env }}.hcx.request.communication"
  kafka_predetermination_topic: "{{ env }}.hcx.request.predetermination"
  kafka_notification_topic: "{{ env }}.hcx.request.notification"
  kafka_subscription_topic: "{{ env }}.hcx.request.subscription"
  kafka_audit_topic: "{{ env }}.hcx.audit"
  kafka_retry_topic: "{{ env }}.hcx.request.retry"
  kafka_onsubscription_topic: "{{ env }}.hcx.request.onsubscription"
  postgres_url: "jdbc:postgresql://{{ hcx_api_postgresql_host }}/postgres"
  es_host: "{{ groups['elasticsearch'][0] }}"
  audit_index: "hcx_audit"
  audit_alias: "hcx_audit"
  postgres_user: "{{ hcx_api_postgresql_user }}"
  postgres_password: "{{ hcx_api_postgresql_password }}"
  postgres_tablename: "payload"
  redis_host: "redis-master.{{ env }}.svc.cluster.local"
  registry_basePath: "http://hcx-registry.{{ env }}.svc.cluster.local:8081"
  registry_hcxcode: "{{ registry_hcx_code }}"
  not_allowed_urls: {{ gateway_not_allowed_urls }}
  hcx_instance_name: {{ hcx_instance_name }}
  certificates_accesskey: {{ certificates_accesskey }}
  certificates_secretKey: {{ certificates_secretKey }}
  certificates_bucketName: {{ certificates_bucketName }}

service:
  type: ClusterIP
