# If your ingress controller has the SSL Termination, you can add the following env vars in extraEnvVars
# Ref: https://github.com/bitnami/charts/tree/master/bitnami/keycloak/#use-with-ingress-offloading-ssl
# extraEnvVars:
#   - name: KEYCLOAK_PROXY_ADDRESS_FORWARDING
#     value: "true"
#   - name: KEYCLOAK_FRONTEND_URL
#     value: "https://keycloak.xxx"

fullnameOverride: keycloak

env:
  DB_VENDOR: postgres
  DB_ADDR: '{{ keycloak_postgresql_host }}'
  DB_PORT: 5432
  DB_DATABASE: keycloak
  DB_USER: '{{ keycloak_postgresql_user }}'
  DB_PASSWORD: '{{ keycloak_postgresql_password }}'
  KEYCLOAK_USER: admin
  KEYCLOAK_PASSWORD: '{{ keycloak_admin_password }}'
  # Comment below if you don't want to initialize the realm
  KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 512m
    memory: 1Gi
