image:
  tag: "{{ image_tag }}"
  repository: "{{ docker_repo }}/hcx-pipeline-jobs"
job_classname: "org.swasth.dp.preauth.task.PreauthStreamTask"
taskManagerAdditionalArgs: []
  # For example
  # - -Dfs.azure.account.key.myblobstorageaccount.blob.core.windows.net=myblobstorageaccountpassword,
jobManagerAdditionalArgs: []
  # For example
  # - -Dfs.azure.account.key.hcxapi.blob.core.windows.net=mysupersecretpassword

