apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: {{ .Release.Namespace }}
data:
  location.list: |-
    location /healthz {
      return 200 'OK';
    }
    location /api/ {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      rewrite /api/(.*) /$1 break;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Host $host;
      proxy_pass http://hcx-api.staging.svc.cluster.local:8080;
    }
    location /auth/realms/swasth-health-claim-exchange/protocol/openid-connect/token {
      proxy_http_version 1.1;
      proxy_set_header Connection "";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Host $host;
      proxy_pass http://keycloak.keycloak.svc.cluster.local:8080;
    }
  sites.conf: |-
    # Ref: https://github.com/openresty/openresty/#resolvconf-parsing
    resolver local=on;
    # Need real ip address for flags in replay.
    # Some LBs will forward real ips as x-forwarded-for
    # So making that as priority
    map $http_x_forwarded_for $real_ip {
        ~^(\d+\.\d+\.\d+\.\d+) $1;
        default $remote_addr;
    }
    map $http_upgrade $connection_upgrade {
      default upgrade;
      '' close;
    }
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      # server_name _;
      {{ .Values.customServerConfigs }}
      include /etc/nginx/conf.d/location.list;
    }
