apiVersion: v1
kind: Secret
metadata:
  name: participant-realm
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  participant_realm.der: |
    {{ .Files.Get "participant_realm_private_key.der" | b64enc }}

---

apiVersion: v1
kind: Secret
metadata:
  name: user-realm
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  user_realm.der: |
    {{ .Files.Get "user_realm_private_key.der" | b64enc }}